[package]
name = "arithmetic-coding"
version = "0.1.0"
edition = "2024"

[dependencies]
biterator = "0.3.0"
log = "0.4.28"
thiserror = "2.0.16"

[dev-dependencies]
test-log = "0.2.18"
quickcheck = "1.0.3"
quickcheck_macros = "1.1.0"
rand = "0.9.2"
